config/routes.rb
Rails.application.routes.draw do
			get 'welcome/index'
			resources :issues do
				resources :tasks
			end
			root 'welcome#index'
		end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/issue.rb
class Issue < ApplicationRecord
		has_many :tasks, dependent: :destroy
		validates :name, presence: true,length: { minimum: 2 }
	end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :issue
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController

		http_basic_authenticate_with name: "dhh", password: "secret", except:[:index, :show]

		def index
			@issues = Issue.all
		end
		def show
			@issue = Issue.find(params[:id])
		end
		def new
			@issue = Issue.new
		end
		def edit
			@issue = Issue.find(params[:id])
		end
		def create
			@issue = Issue.new(issue_params)
			if @issue.save
				redirect_to @issue
			else
				render 'new'
			end
		end
		def update
			@issue = Issue.find(params[:id])
			if @issue.update(issue_params)
				redirect_to @issue
			else
				render 'edit'
			end
		end
		def destroy
			@issue = Issue.find(params[:id])
			@issue.destroy
			redirect_to issues_path
		end
		private
			def issue_params
				params.require(:issue).permit(:name, :ticket, :desc, :resolute, :notes)
			end
	end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

		http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy

		def create
			@issue = Issue.find(params[:issue_id])
			@task = @issue.tasks.create(task_params)
			redirect_to issue_path(@issue)
		end
		def destroy
			@issue = Issue.find(params[:issue_id])
			@task = @issue.tasks.find(params[:id])
			@task.destroy
			redirect_to issue_path(@issue)
		end
		private
			def task_params
				params.require(:task).permit(:name, :notes)
			end
	end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/issues/_form.html.erb
<%= form_with model: @issue, local: true do |form| %>
		<% if @issue.errors.any? %>
			<div id="error_explanation">
				<h2>
					<%= pluralize(@issue.errors.count, "error") %> prohibited
					this issue from being saved:
				</h2>
				<ul>
					<% @issue.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>
					<% end %>
				</ul>
			</div>
		<% end %>
		<p>
			<%= form.label :name %><br>
			<%= form.text_field :name %>
		</p>
		<p>
			<%= form.label :ticket %><br>
			<%= form.text_field :ticket %>
		</p>
    <p>
			<%= form.label :description %><br>
			<%= form.text_area :desc %>
		</p>
    <p>
			<%= form.label :Resolution %><br>
			<%= form.text_area :resolute %>
		</p>
    <p>
			<%= form.label :Notes %><br>
			<%= form.text_area :notes %>
		</p>
		<p>
			<%= form.submit %>
		</p>
	<% end %>

app/views/issues/edit.html.erb
<h4>Update this issue</h4>
	<%= render 'form' %>
	<%= link_to 'Back', issues_path %>

app/views/issues/index.html.erb
<h4>Listing CPR+ Issues</h4>
<hr>
	<%= link_to 'New Issue', new_issue_path %>
<hr>
	<table>
	<tr>
		<th>Ticket</th>
		<th>Name</th>
    <th colspan="3">Actions</th>
	</tr>
	<% @issues.each do |issue| %>
	<tr>

    <td><%= issue.ticket %></td>
		<td><%= issue.name %></td>
		<td><%= link_to 'Show', issue_path(issue) %></td>
		<td><%= link_to 'Edit', edit_issue_path(issue) %></td>
		<td><%= link_to 'Destroy', issue_path(issue),
			method: :delete,
			data: { confirm: 'Are you sure?' } %></td>
	</tr>
	<% end %>
	</table>

app/views/issues/new.html.erb
<h1>New Issue</h1>
	<%= render 'form' %>
	<%= link_to 'Back', issues_path %>

app/views/issues/show.html.erb
<p><strong><%= @issue.name %></strong></p>
<p><strong>Ticket:</strong><%= @issue.ticket %></p>
<p><strong>Description:</strong><%= @issue.desc %></p>
<p><strong>Resolution:</strong><%= @issue.resolute %></p>
<p><strong>Notes:</strong><%= @issue.notes %></p>

<hr>
<h4>Tasks</h4>
<%= render @issue.tasks %>

<hr>
<h5>Add a task:</h5>
<%= render 'tasks/form' %>
<%= link_to 'Edit', edit_issue_path(@issue) %> |
<%= link_to 'Back', issues_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cpr</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: [ @issue, @issue.tasks.build ], local: true) do |form| %>
		<p><%= form.label :name %><br><%= form.text_field :name %></p>
		<p><%= form.label :notes %><br><%= form.text_area :notes %></p>
		<p><%= form.submit %></p>
	<% end %>

app/views/tasks/_task.html.erb
<p><strong>Name:</strong><%= task.name %></p>
	<p><strong>Description:</strong><%= task.notes %></p>
	<p>
	<%= link_to 'Destroy Task', [task.issue, task],
	method: :delete,
	data: { confirm: 'Are you sure?' } %>
	</p>

app/views/welcome/index.html.erb
<h1>WellSky CPR+ Issues</h1>
<br>
<%= link_to 'List of Issues', issues_path %>